apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: yaml-instance-v5
  namespace: default
spec:
  clusterServiceClassExternalName: ecs-bucket
  clusterServicePlanExternalName: 10gb
  parameters:
    reclaim-policy: Delete
