apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: yaml-instance-v2
  namespace: catalog
spec:
  clusterServiceClassExternalName: ecs-bucket
  clusterServicePlanExternalName: 5gb
