apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: yaml-instance-v4
  namespace: default
spec:
  clusterServiceClassExternalName: ecs-bucket
  clusterServicePlanExternalName: 10gb
  reclaim-policy: Delete
